version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d etl_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_service:
    build: ./api_service
    env_file:
      - .env
    volumes:
      - shared_data:/app/shared_data
    command: ["python", "extract_data.py"]

  transform_service:
    build: ./transform_service
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - shared_data:/app/shared_data
    command: ["python", "transform_data.py"]

volumes:
  shared_data:
